#!/usr/bin/env python
#
#  Check how many collisions occur in table using id based on truncated hash.
#
import os, sys
import MySQLdb as db

hits = {}
last = 0
run = 0
total = 0

count = int(sys.argv[1]) if len(sys.argv) > 1 else 0

sql = db.connect('localhost','btc','test623btc','bitcoin')
cur = sql.cursor()
if count > 0:
    cur.execute('select id from address limit %s', (count,))
else:
    cur.execute('select id from address')
    
for row in cur:
    if row[0] == last+2:
        run += 1
    elif run > 0:
        if run in hits:
            hits[run] += 1
        else:
            hits[run] = 1
        run = 0
    last = row[0]

for slot,hit in sorted(hits.items()):
    print slot,'-',hit
    total += hit*slot
    
print "\nTotal Hits:", total
if count > 0:
    print "Ratio: 1 in ", int(count/total)
    


    
