
CREATE TABLE "blocks" ("id" INTEGER PRIMARY KEY NOT NULL ,"hash" BLOB NOT NULL ,"hdr" BLOB NOT NULL);
CREATE TABLE "trxs" ("id" INTEGER PRIMARY KEY NOT NULL ,"hash" BLOB NOT NULL ,"inputs" BLOB, "block_id" INTEGER);
CREATE TABLE "outputs" ("id" INTEGER PRIMARY KEY NOT NULL ,"value" INTEGER,"addr_id" INTEGER NOT NULL, "sig" INTEGER,"pk" INTEGER ) WITHOUT ROWID;
CREATE TABLE "address" ("id" INTEGER PRIMARY KEY NOT NULL, "addr" BLOB NOT NULL );
