DROP DATABASE IF EXISTS bitcoin;
CREATE DATABASE bitcoin;
USE bitcoin;
CREATE TABLE `blocks` (`id` INTEGER PRIMARY KEY NOT NULL ,`hash` BINARY(32) NOT NULL ,`hdr` VARBINARY(180) NOT NULL ) ENGINE=MYISAM;
CREATE TABLE `trxs` (`id` DECIMAL(13) PRIMARY KEY NOT NULL , `hash` BINARY(37) NOT NULL , `txdata` DECIMAL(13), `block_id` INTEGER) ENGINE=MYISAM;
CREATE TABLE `outputs` (`id` DECIMAL(15) PRIMARY KEY NOT NULL ,`value` DECIMAL(16),`addr_id` DECIMAL(13),`tx_id` DECIMAL(13) ) ENGINE=MYISAM;
CREATE TABLE `address` (`id` DECIMAL(13) PRIMARY KEY NOT NULL , `addr` BINARY(20) NOT NULL) ENGINE=MYISAM;


