CREATE TABLE `blocks` (`id` INTEGER NOT NULL ,`hash` BLOB NOT NULL ,`hdr` BLOB NOT NULL , `coinbase` BLOB ) ENGINE=MYISAM;
CREATE TABLE `trxs` (`id` DECIMAL(13) NOT NULL , `hash` BLOB NOT NULL , `inputs` BLOB, `block_id` INTEGER) ENGINE=MYISAM;
CREATE TABLE `outputs` (`id` DECIMAL(15) NOT NULL ,`value` DECIMAL(16),`addr_id` DECIMAL(13),`sig` DECIMAL(13) ,`pk` DECIMAL(13) ) ENGINE=MYISAM;
CREATE TABLE `address` (`id` DECIMAL(13) NOT NULL , `addr` BLOB NOT NULL) ENGINE=MYISAM;

