DROP DATABASE BITCOIN;
CREATE DATABASE BITCOIN;
USE BITCOIN;
CREATE TABLE `blocks` (`id` INTEGER PRIMARY KEY NOT NULL ,`hash` BINARY(32) NOT NULL ,`hdr` VARBINARY(180) NOT NULL ) ENGINE=MYISAM;
CREATE TABLE `trxs` (`id` DECIMAL(13) PRIMARY KEY NOT NULL , `hash` BINARY(37) NOT NULL , `inputs` BLOB, `block_id` INTEGER) ENGINE=MYISAM;
CREATE TABLE `outputs` (`id` DECIMAL(15) PRIMARY KEY NOT NULL ,`value` DECIMAL(16),`addr_id` DECIMAL(13),`sig` DECIMAL(13) ,`pk` DECIMAL(13) ) ENGINE=MYISAM;
CREATE TABLE `address` (`id` DECIMAL(13) PRIMARY KEY NOT NULL , `addr` BINARY(20) NOT NULL) ENGINE=MYISAM;


