#!/bin/bash

if [ -e 'btcGate.pid' ]; then
  if [ "$1" == "stop" ]; then
    kill -SIGTERM `cat btcGate.pid`
    bp=`pgrep -o btcGate`
    kill -15 -`ps h -o pgid $bp`
    rm btcGate.pid
  fi
  exit 0
fi

ssh -fqND 9050 -p 36000 localhost
echo $(lsof -t -i @localhost:9050 -sTCP:listen) >btcGate.pid
{
while true
do
  nc -lp 8338 |  while read  cmd
  do
  if [ "$cmd" == "resume" ] && [ ! -e btcGate.pid ]; then
    ssh -fqND 9050 -p 36000 localhost
    echo $(lsof -t -i @localhost:9050 -sTCP:listen) >btcGate.pid
  elif [ "$cmd" == "pause" ] && [ -e btcGate.pid ]; then
    kill -SIGTERM `cat btcGate.pid`
    rm btcGate.pid
  fi
  done
done
} &
