#!/usr/bin/env python
#
#   fix blksize when missing
#

cfg = { 'dbinfo':"localhost:btc:pwd:testnet", 'path':'/var/data/sqlchain/testnet' }

blk = 0
max_blk = 907843

import MySQLdb as db

sql = db.connect(*cfg['dbinfo'].split(':'))
cur = sql.cursor()

fixlist = []
while blk < max_blk:
    cur.execute("select count(*),sum(txsize) from trxs where block_id>=%s and block_id <%s;", (blk*20000,(blk+1)*20000))
    txcnt,blksize = cur.fetchone()
    blksize += 81 if txcnt <= 252 else 83 
    fixlist.append((blksize,blk))
    if blk % 10000 == 0:
        print "Commit:",blk
        cur.executemany("update blocks set blksize=%s where id=%s;", fixlist)
        sql.commit()
        fixlist = []
    blk += 1

cur.executemany("update blocks set blksize=%s where id=%s;", fixlist)
sql.commit()

print "Done",blk

